CREATE TABLE SCALA.DISCOUNT
(
  ORDER_DATE      DATE,
  PRODUCT_NAME    VARCHAR2(100 BYTE),
  EXPIRY_DATE     DATE,
  QUANTITY        NUMBER,
  UNIT_PRICE      NUMBER,
  DISCOUNT        VARCHAR2(10 BYTE),
  FINAL_PRICE     NUMBER,
  CHANNEL         VARCHAR2(50 BYTE),
  PAYMENT_METHOD  VARCHAR2(50 BYTE)
)
